class AddJfVocab < ActiveRecord::Migration
      def self.up
        Vocentry.delete_all
        Vocentry.create(:eng_word => "abate", :frequency => 1) 
        Vocentry.create(:eng_word => "abjure", :frequency => 1) 
        Vocentry.create(:eng_word => "act up", :frequency => 1) 
        Vocentry.create(:eng_word => "act upon them", :frequency => 1) 
        Vocentry.create(:eng_word => "acute", :frequency => 1) 
        Vocentry.create(:eng_word => "ad hoc", :frequency => 1) 
        Vocentry.create(:eng_word => "adamant", :frequency => 1) 
        Vocentry.create(:eng_word => "adroit", :frequency => 1) 
        Vocentry.create(:eng_word => "aggravate", :frequency => 1) 
        Vocentry.create(:eng_word => "aghast", :frequency => 1) 
        Vocentry.create(:eng_word => "aloof", :frequency => 1) 
        Vocentry.create(:eng_word => "angst", :frequency => 1) 
        Vocentry.create(:eng_word => "anticipation", :frequency => 1) 
        Vocentry.create(:eng_word => "anything goes", :frequency => 1) 
        Vocentry.create(:eng_word => "apocryphal", :frequency => 1) 
        Vocentry.create(:eng_word => "apocryphal quote", :frequency => 1) 
        Vocentry.create(:eng_word => "appalling", :frequency => 1) 
        Vocentry.create(:eng_word => "appealing", :frequency => 1) 
        Vocentry.create(:eng_word => "arguably", :frequency => 1) 
        Vocentry.create(:eng_word => "arraigned", :frequency => 1) 
        Vocentry.create(:eng_word => "assertive", :frequency => 1) 
        Vocentry.create(:eng_word => "at odds", :frequency => 1) 
        Vocentry.create(:eng_word => "at the latest", :frequency => 1) 
        Vocentry.create(:eng_word => "attrition", :frequency => 1) 
        Vocentry.create(:eng_word => "awash", :frequency => 1) 
        Vocentry.create(:eng_word => "awkward", :frequency => 1) 
        Vocentry.create(:eng_word => "back and forth", :frequency => 1) 
        Vocentry.create(:eng_word => "baffled by", :frequency => 1) 
        Vocentry.create(:eng_word => "bail out", :frequency => 1) 
        Vocentry.create(:eng_word => "bailout", :frequency => 1) 
        Vocentry.create(:eng_word => "ballgown", :frequency => 1) 
        Vocentry.create(:eng_word => "baloney", :frequency => 1) 
        Vocentry.create(:eng_word => "bar none", :frequency => 1) 
        Vocentry.create(:eng_word => "bar one", :frequency => 1) 
        Vocentry.create(:eng_word => "bash", :frequency => 1) 
        Vocentry.create(:eng_word => "bawdy", :frequency => 1) 
        Vocentry.create(:eng_word => "be gutted by", :frequency => 1) 
        Vocentry.create(:eng_word => "be in a funk", :frequency => 1) 
        Vocentry.create(:eng_word => "be loath", :frequency => 1) 
        Vocentry.create(:eng_word => "beaming", :frequency => 1) 
        Vocentry.create(:eng_word => "become moot", :frequency => 1) 
        Vocentry.create(:eng_word => "bedspread", :frequency => 1) 
        Vocentry.create(:eng_word => "beforehand", :frequency => 1) 
        Vocentry.create(:eng_word => "begrudgingly", :frequency => 1) 
        Vocentry.create(:eng_word => "beguile", :frequency => 1) 
        Vocentry.create(:eng_word => "behemoth", :frequency => 1) 
        Vocentry.create(:eng_word => "being scammed", :frequency => 1) 
        Vocentry.create(:eng_word => "belated", :frequency => 1) 
        Vocentry.create(:eng_word => "beleaguered", :frequency => 1) 
        Vocentry.create(:eng_word => "bemoan", :frequency => 1) 
        Vocentry.create(:eng_word => "berate", :frequency => 1) 
        Vocentry.create(:eng_word => "beset", :frequency => 1) 
        Vocentry.create(:eng_word => "bestow", :frequency => 1) 
        Vocentry.create(:eng_word => "bestride", :frequency => 1) 
        Vocentry.create(:eng_word => "bestriding", :frequency => 1) 
        Vocentry.create(:eng_word => "bias", :frequency => 1) 
        Vocentry.create(:eng_word => "bickering", :frequency => 1) 
        Vocentry.create(:eng_word => "big rig", :frequency => 1) 
        Vocentry.create(:eng_word => "big time", :frequency => 1) 
        Vocentry.create(:eng_word => "binge", :frequency => 1) 
        Vocentry.create(:eng_word => "biomes", :frequency => 1) 
        Vocentry.create(:eng_word => "blather", :frequency => 1) 
        Vocentry.create(:eng_word => "bleak", :frequency => 1) 
        Vocentry.create(:eng_word => "bleak", :frequency => 1) 
        Vocentry.create(:eng_word => "bleech hair", :frequency => 1) 
        Vocentry.create(:eng_word => "blithely", :frequency => 1) 
        Vocentry.create(:eng_word => "blow", :frequency => 1) 
        Vocentry.create(:eng_word => "blow up", :frequency => 1) 
        Vocentry.create(:eng_word => "bluestery", :frequency => 1) 
        Vocentry.create(:eng_word => "blunder", :frequency => 1) 
        Vocentry.create(:eng_word => "bolster", :frequency => 1) 
        Vocentry.create(:eng_word => "botus of laughter", :frequency => 1) 
        Vocentry.create(:eng_word => "boulder", :frequency => 1) 
        Vocentry.create(:eng_word => "bout", :frequency => 1) 
        Vocentry.create(:eng_word => "bow out", :frequency => 1) 
        Vocentry.create(:eng_word => "brash", :frequency => 1) 
        Vocentry.create(:eng_word => "brawn", :frequency => 1) 
        Vocentry.create(:eng_word => "broody", :frequency => 1) 
        Vocentry.create(:eng_word => "buck up", :frequency => 1) 
        Vocentry.create(:eng_word => "bulky", :frequency => 1) 
        Vocentry.create(:eng_word => "bullock", :frequency => 1) 
        Vocentry.create(:eng_word => "bust", :frequency => 1) 
        Vocentry.create(:eng_word => "buttress", :frequency => 1) 
        Vocentry.create(:eng_word => "by a fluke", :frequency => 1) 
        Vocentry.create(:eng_word => "by and by", :frequency => 1) 
        Vocentry.create(:eng_word => "cackles", :frequency => 1) 
        Vocentry.create(:eng_word => "cagy/cagey", :frequency => 1) 
        Vocentry.create(:eng_word => "cantankerous", :frequency => 1) 
        Vocentry.create(:eng_word => "carve up", :frequency => 1) 
        Vocentry.create(:eng_word => "catharsis", :frequency => 1) 
        Vocentry.create(:eng_word => "chatty", :frequency => 1) 
        Vocentry.create(:eng_word => "cheesy", :frequency => 1) 
        Vocentry.create(:eng_word => "chest", :frequency => 1) 
        Vocentry.create(:eng_word => "chicanery", :frequency => 1) 
        Vocentry.create(:eng_word => "chuck it all", :frequency => 1) 
        Vocentry.create(:eng_word => "cinch", :frequency => 1) 
        Vocentry.create(:eng_word => "circumvent", :frequency => 1) 
        Vocentry.create(:eng_word => "clam", :frequency => 1) 
        Vocentry.create(:eng_word => "clammy", :frequency => 1) 
        Vocentry.create(:eng_word => "clash", :frequency => 1) 
        Vocentry.create(:eng_word => "clerical", :frequency => 1) 
        Vocentry.create(:eng_word => "clinging", :frequency => 1) 
        Vocentry.create(:eng_word => "clingy", :frequency => 1) 
        Vocentry.create(:eng_word => "clotting", :frequency => 1) 
        Vocentry.create(:eng_word => "clunky", :frequency => 1) 
        Vocentry.create(:eng_word => "coal", :frequency => 1) 
        Vocentry.create(:eng_word => "cobble", :frequency => 1) 
        Vocentry.create(:eng_word => "coddled", :frequency => 1) 
        Vocentry.create(:eng_word => "coerce", :frequency => 1) 
        Vocentry.create(:eng_word => "colloquial (understand) entender coloquial", :frequency => 1) 
        Vocentry.create(:eng_word => "con", :frequency => 1) 
        Vocentry.create(:eng_word => "concussion", :frequency => 1) 
        Vocentry.create(:eng_word => "conspicuous", :frequency => 1) 
        Vocentry.create(:eng_word => "consummate", :frequency => 1) 
        Vocentry.create(:eng_word => "contempt desprecio m", :frequency => 1) 
        Vocentry.create(:eng_word => "contemptuous", :frequency => 1) 
        Vocentry.create(:eng_word => "contrite", :frequency => 1) 
        Vocentry.create(:eng_word => "conundrum", :frequency => 1) 
        Vocentry.create(:eng_word => "coo", :frequency => 1) 
        Vocentry.create(:eng_word => "cornucopia", :frequency => 1) 
        Vocentry.create(:eng_word => "corny", :frequency => 1) 
        Vocentry.create(:eng_word => "corrugated", :frequency => 1) 
        Vocentry.create(:eng_word => "counterintuitive", :frequency => 1) 
        Vocentry.create(:eng_word => "cradle", :frequency => 1) 
        Vocentry.create(:eng_word => "cranky", :frequency => 1) 
        Vocentry.create(:eng_word => "creases (n)", :frequency => 1) 
        Vocentry.create(:eng_word => "croak", :frequency => 1) 
        Vocentry.create(:eng_word => "cronyism", :frequency => 1) 
        Vocentry.create(:eng_word => "crotch", :frequency => 1) 
        Vocentry.create(:eng_word => "crowed", :frequency => 1) 
        Vocentry.create(:eng_word => "crummy", :frequency => 1) 
        Vocentry.create(:eng_word => "cub", :frequency => 1) 
        Vocentry.create(:eng_word => "cubs", :frequency => 1) 
        Vocentry.create(:eng_word => "cunning", :frequency => 1) 
        Vocentry.create(:eng_word => "curd", :frequency => 1) 
        Vocentry.create(:eng_word => "dabble", :frequency => 1) 
        Vocentry.create(:eng_word => "dally", :frequency => 1) 
        Vocentry.create(:eng_word => "dashing", :frequency => 1) 
        Vocentry.create(:eng_word => "dazzling", :frequency => 1) 
        Vocentry.create(:eng_word => "deacon", :frequency => 1) 
        Vocentry.create(:eng_word => "deadlock", :frequency => 1) 
        Vocentry.create(:eng_word => "deadpan", :frequency => 1) 
        Vocentry.create(:eng_word => "dearth", :frequency => 1) 
        Vocentry.create(:eng_word => "deceit", :frequency => 1) 
        Vocentry.create(:eng_word => "deferred", :frequency => 1) 
        Vocentry.create(:eng_word => "deft", :frequency => 1) 
        Vocentry.create(:eng_word => "demeaning", :frequency => 1) 
        Vocentry.create(:eng_word => "demeanor", :frequency => 1) 
        Vocentry.create(:eng_word => "demurred", :frequency => 1) 
        Vocentry.create(:eng_word => "dent (being dented)", :frequency => 1) 
        Vocentry.create(:eng_word => "dependable", :frequency => 1) 
        Vocentry.create(:eng_word => "deputize for", :frequency => 1) 
        Vocentry.create(:eng_word => "deputy", :frequency => 1) 
        Vocentry.create(:eng_word => "devise", :frequency => 1) 
        Vocentry.create(:eng_word => "devoid of", :frequency => 1) 
        Vocentry.create(:eng_word => "dicey", :frequency => 1) 
        Vocentry.create(:eng_word => "die", :frequency => 1) 
        Vocentry.create(:eng_word => "digress", :frequency => 1) 
        Vocentry.create(:eng_word => "digress from", :frequency => 1) 
        Vocentry.create(:eng_word => "disclosure", :frequency => 1) 
        Vocentry.create(:eng_word => "discretionary", :frequency => 1) 
        Vocentry.create(:eng_word => "disgruntled /d_s'gr_nt_d/ adjetivo ‹child/look› contrariado", :frequency => 1) 
        Vocentry.create(:eng_word => "dish up", :frequency => 1) 
        Vocentry.create(:eng_word => "disrepute", :frequency => 1) 
        Vocentry.create(:eng_word => "dissing", :frequency => 1) 
        Vocentry.create(:eng_word => "distracting", :frequency => 1) 
        Vocentry.create(:eng_word => "distraught", :frequency => 1) 
        Vocentry.create(:eng_word => "ditty", :frequency => 1) 
        Vocentry.create(:eng_word => "dive bar", :frequency => 1) 
        Vocentry.create(:eng_word => "diverter spout", :frequency => 1) 
        Vocentry.create(:eng_word => "do me on it", :frequency => 1) 
        Vocentry.create(:eng_word => "dodge", :frequency => 1) 
        Vocentry.create(:eng_word => "dogging", :frequency => 1) 
        Vocentry.create(:eng_word => "dole out", :frequency => 1) 
        Vocentry.create(:eng_word => "dong", :frequency => 1) 
        Vocentry.create(:eng_word => "doozy", :frequency => 1) 
        Vocentry.create(:eng_word => "dork", :frequency => 1) 
        Vocentry.create(:eng_word => "douchebag", :frequency => 1) 
        Vocentry.create(:eng_word => "dread", :frequency => 1) 
        Vocentry.create(:eng_word => "dreary", :frequency => 1) 
        Vocentry.create(:eng_word => "drench", :frequency => 1) 
        Vocentry.create(:eng_word => "dribble", :frequency => 1) 
        Vocentry.create(:eng_word => "drooped to the teens", :frequency => 1) 
        Vocentry.create(:eng_word => "drop off", :frequency => 1) 
        Vocentry.create(:eng_word => "droves", :frequency => 1) 
        Vocentry.create(:eng_word => "drudgery", :frequency => 1) 
        Vocentry.create(:eng_word => "dry up", :frequency => 1) 
        Vocentry.create(:eng_word => "due up front", :frequency => 1) 
        Vocentry.create(:eng_word => "dullard", :frequency => 1) 
        Vocentry.create(:eng_word => "dusky", :frequency => 1) 
        Vocentry.create(:eng_word => "dwell on", :frequency => 1) 
        Vocentry.create(:eng_word => "dwindle", :frequency => 1) 
        Vocentry.create(:eng_word => "dystopia", :frequency => 1) 
        Vocentry.create(:eng_word => "earnest", :frequency => 1) 
        Vocentry.create(:eng_word => "earnestly", :frequency => 1) 
        Vocentry.create(:eng_word => "eat up", :frequency => 1) 
        Vocentry.create(:eng_word => "edgy", :frequency => 1) 
        Vocentry.create(:eng_word => "eery", :frequency => 1) 
        Vocentry.create(:eng_word => "eery", :frequency => 1) 
        Vocentry.create(:eng_word => "egregious", :frequency => 1) 
        Vocentry.create(:eng_word => "endearment", :frequency => 1) 
        Vocentry.create(:eng_word => "engrossed", :frequency => 1) 
        Vocentry.create(:eng_word => "ensconce", :frequency => 1) 
        Vocentry.create(:eng_word => "ensconced", :frequency => 1) 
        Vocentry.create(:eng_word => "entanglement", :frequency => 1) 
        Vocentry.create(:eng_word => "enthrall", :frequency => 1) 
        Vocentry.create(:eng_word => "entice", :frequency => 1) 
        Vocentry.create(:eng_word => "enticing", :frequency => 1) 
        Vocentry.create(:eng_word => "entry", :frequency => 1) 
        Vocentry.create(:eng_word => "epistemology", :frequency => 1) 
        Vocentry.create(:eng_word => "equivocate", :frequency => 1) 
        Vocentry.create(:eng_word => "errand", :frequency => 1) 
        Vocentry.create(:eng_word => "eschewed", :frequency => 1) 
        Vocentry.create(:eng_word => "esoteric", :frequency => 1) 
        Vocentry.create(:eng_word => "exegesis", :frequency => 1) 
        Vocentry.create(:eng_word => "exhort", :frequency => 1) 
        Vocentry.create(:eng_word => "extol", :frequency => 1) 
        Vocentry.create(:eng_word => "facetious", :frequency => 1) 
        Vocentry.create(:eng_word => "fastidious", :frequency => 1) 
        Vocentry.create(:eng_word => "fault", :frequency => 1) 
        Vocentry.create(:eng_word => "feckless", :frequency => 1) 
        Vocentry.create(:eng_word => "fed wards", :frequency => 1) 
        Vocentry.create(:eng_word => "feisty", :frequency => 1) 
        Vocentry.create(:eng_word => "fellow", :frequency => 1) 
        Vocentry.create(:eng_word => "fester", :frequency => 1) 
        Vocentry.create(:eng_word => "feud", :frequency => 1) 
        Vocentry.create(:eng_word => "fey", :frequency => 1) 
        Vocentry.create(:eng_word => "fibs", :frequency => 1) 
        Vocentry.create(:eng_word => "fidget", :frequency => 1) 
        Vocentry.create(:eng_word => "filth", :frequency => 1) 
        Vocentry.create(:eng_word => "flabbergasted", :frequency => 1) 
        Vocentry.create(:eng_word => "flabby", :frequency => 1) 
        Vocentry.create(:eng_word => "flail", :frequency => 1) 
        Vocentry.create(:eng_word => "flapping gums", :frequency => 1) 
        Vocentry.create(:eng_word => "flaundered", :frequency => 1) 
        Vocentry.create(:eng_word => "flaunt", :frequency => 1) 
        Vocentry.create(:eng_word => "fledge", :frequency => 1) 
        Vocentry.create(:eng_word => "fledgling", :frequency => 1) 
        Vocentry.create(:eng_word => "flee", :frequency => 1) 
        Vocentry.create(:eng_word => "fleet", :frequency => 1) 
        Vocentry.create(:eng_word => "fleeting", :frequency => 1) 
        Vocentry.create(:eng_word => "fling (n)", :frequency => 1) 
        Vocentry.create(:eng_word => "flip off", :frequency => 1) 
        Vocentry.create(:eng_word => "flip out", :frequency => 1) 
        Vocentry.create(:eng_word => "flits", :frequency => 1) 
        Vocentry.create(:eng_word => "flog", :frequency => 1) 
        Vocentry.create(:eng_word => "fluff", :frequency => 1) 
        Vocentry.create(:eng_word => "fluke", :frequency => 1) 
        Vocentry.create(:eng_word => "flummery", :frequency => 1) 
        Vocentry.create(:eng_word => "flunk", :frequency => 1) 
        Vocentry.create(:eng_word => "flush", :frequency => 1) 
        Vocentry.create(:eng_word => "flutter", :frequency => 1) 
        Vocentry.create(:eng_word => "follow through", :frequency => 1) 
        Vocentry.create(:eng_word => "foreclosure", :frequency => 1) 
        Vocentry.create(:eng_word => "forswears", :frequency => 1) 
        Vocentry.create(:eng_word => "forthright", :frequency => 1) 
        Vocentry.create(:eng_word => "fortnight", :frequency => 1) 
        Vocentry.create(:eng_word => "frame", :frequency => 1) 
        Vocentry.create(:eng_word => "fraying", :frequency => 1) 
        Vocentry.create(:eng_word => "freak out", :frequency => 1) 
        Vocentry.create(:eng_word => "fretter", :frequency => 1) 
        Vocentry.create(:eng_word => "fritter away", :frequency => 1) 
        Vocentry.create(:eng_word => "frolic", :frequency => 1) 
        Vocentry.create(:eng_word => "frumpy", :frequency => 1) 
        Vocentry.create(:eng_word => "furlough", :frequency => 1) 
        Vocentry.create(:eng_word => "furrows", :frequency => 1) 
        Vocentry.create(:eng_word => "fussy", :frequency => 1) 
        Vocentry.create(:eng_word => "garish", :frequency => 1) 
        Vocentry.create(:eng_word => "gear up for", :frequency => 1) 
        Vocentry.create(:eng_word => "geniality", :frequency => 1) 
        Vocentry.create(:eng_word => "germane", :frequency => 1) 
        Vocentry.create(:eng_word => "get a glimpse of", :frequency => 1) 
        Vocentry.create(:eng_word => "get a grip", :frequency => 1) 
        Vocentry.create(:eng_word => "get around", :frequency => 1) 
        Vocentry.create(:eng_word => "get one head around", :frequency => 1) 
        Vocentry.create(:eng_word => "ghastly", :frequency => 1) 
        Vocentry.create(:eng_word => "giddy", :frequency => 1) 
        Vocentry.create(:eng_word => "gilded", :frequency => 1) 
        Vocentry.create(:eng_word => "gill", :frequency => 1) 
        Vocentry.create(:eng_word => "gimmicks", :frequency => 1) 
        Vocentry.create(:eng_word => "girth", :frequency => 1) 
        Vocentry.create(:eng_word => "gist", :frequency => 1) 
        Vocentry.create(:eng_word => "give the cold shoulder", :frequency => 1) 
        Vocentry.create(:eng_word => "giveaway", :frequency => 1) 
        Vocentry.create(:eng_word => "gloat", :frequency => 1) 
        Vocentry.create(:eng_word => "glum / gloomy", :frequency => 1) 
        Vocentry.create(:eng_word => "goaded", :frequency => 1) 
        Vocentry.create(:eng_word => "gobbled up", :frequency => 1) 
        Vocentry.create(:eng_word => "gobbledygook", :frequency => 1) 
        Vocentry.create(:eng_word => "gobs", :frequency => 1) 
        Vocentry.create(:eng_word => "gooey", :frequency => 1) 
        Vocentry.create(:eng_word => "gown", :frequency => 1) 
        Vocentry.create(:eng_word => "graft", :frequency => 1) 
        Vocentry.create(:eng_word => "grasp", :frequency => 1) 
        Vocentry.create(:eng_word => "graze", :frequency => 1) 
        Vocentry.create(:eng_word => "greedy", :frequency => 1) 
        Vocentry.create(:eng_word => "griddles", :frequency => 1) 
        Vocentry.create(:eng_word => "grin", :frequency => 1) 
        Vocentry.create(:eng_word => "grind my gears", :frequency => 1) 
        Vocentry.create(:eng_word => "grinding", :frequency => 1) 
        Vocentry.create(:eng_word => "grit", :frequency => 1) 
        Vocentry.create(:eng_word => "gross / yukky", :frequency => 1) 
        Vocentry.create(:eng_word => "groundswell", :frequency => 1) 
        Vocentry.create(:eng_word => "grudges", :frequency => 1) 
        Vocentry.create(:eng_word => "grueling", :frequency => 1) 
        Vocentry.create(:eng_word => "grunt", :frequency => 1) 
        Vocentry.create(:eng_word => "gummed up", :frequency => 1) 
        Vocentry.create(:eng_word => "gurgle", :frequency => 1) 
        Vocentry.create(:eng_word => "gusty", :frequency => 1) 
        Vocentry.create(:eng_word => "haggle", :frequency => 1) 
        Vocentry.create(:eng_word => "haggle (over sthgh)", :frequency => 1) 
        Vocentry.create(:eng_word => "haltingly", :frequency => 1) 
        Vocentry.create(:eng_word => "hamper", :frequency => 1) 
        Vocentry.create(:eng_word => "hampered", :frequency => 1) 
        Vocentry.create(:eng_word => "hamstrung", :frequency => 1) 
        Vocentry.create(:eng_word => "handicapper", :frequency => 1) 
        Vocentry.create(:eng_word => "haphazard", :frequency => 1) 
        Vocentry.create(:eng_word => "harbinger", :frequency => 1) 
        Vocentry.create(:eng_word => "hardship", :frequency => 1) 
        Vocentry.create(:eng_word => "harp on", :frequency => 1) 
        Vocentry.create(:eng_word => "has had a fit", :frequency => 1) 
        Vocentry.create(:eng_word => "hasty", :frequency => 1) 
        Vocentry.create(:eng_word => "hatching", :frequency => 1) 
        Vocentry.create(:eng_word => "haughty", :frequency => 1) 
        Vocentry.create(:eng_word => "haul", :frequency => 1) 
        Vocentry.create(:eng_word => "have a hunch", :frequency => 1) 
        Vocentry.create(:eng_word => "havoc", :frequency => 1) 
        Vocentry.create(:eng_word => "head rush", :frequency => 1) 
        Vocentry.create(:eng_word => "heartbreaking", :frequency => 1) 
        Vocentry.create(:eng_word => "heckle", :frequency => 1) 
        Vocentry.create(:eng_word => "hedged", :frequency => 1) 
        Vocentry.create(:eng_word => "heed", :frequency => 1) 
        Vocentry.create(:eng_word => "hefty", :frequency => 1) 
        Vocentry.create(:eng_word => "heinie", :frequency => 1) 
        Vocentry.create(:eng_word => "heir", :frequency => 1) 
        Vocentry.create(:eng_word => "heirloom", :frequency => 1) 
        Vocentry.create(:eng_word => "hew", :frequency => 1) 
        Vocentry.create(:eng_word => "hiatus", :frequency => 1) 
        Vocentry.create(:eng_word => "hideous", :frequency => 1) 
        Vocentry.create(:eng_word => "hieratic", :frequency => 1) 
        Vocentry.create(:eng_word => "high and mighty", :frequency => 1) 
        Vocentry.create(:eng_word => "hilt", :frequency => 1) 
        Vocentry.create(:eng_word => "hinder", :frequency => 1) 
        Vocentry.create(:eng_word => "hindrance", :frequency => 1) 
        Vocentry.create(:eng_word => "hinge on", :frequency => 1) 
        Vocentry.create(:eng_word => "hinky", :frequency => 1) 
        Vocentry.create(:eng_word => "hissy", :frequency => 1) 
        Vocentry.create(:eng_word => "hissy fits", :frequency => 1) 
        Vocentry.create(:eng_word => "hit it off", :frequency => 1) 
        Vocentry.create(:eng_word => "hoarse", :frequency => 1) 
        Vocentry.create(:eng_word => "hobble", :frequency => 1) 
        Vocentry.create(:eng_word => "hoist", :frequency => 1) 
        Vocentry.create(:eng_word => "hoist and hold", :frequency => 1) 
        Vocentry.create(:eng_word => "hollow", :frequency => 1) 
        Vocentry.create(:eng_word => "hoof", :frequency => 1) 
        Vocentry.create(:eng_word => "hoot", :frequency => 1) 
        Vocentry.create(:eng_word => "hortative", :frequency => 1) 
        Vocentry.create(:eng_word => "hosiery", :frequency => 1) 
        Vocentry.create(:eng_word => "hubristic", :frequency => 1) 
        Vocentry.create(:eng_word => "huddle", :frequency => 1) 
        Vocentry.create(:eng_word => "hunch", :frequency => 1) 
        Vocentry.create(:eng_word => "hunk", :frequency => 1) 
        Vocentry.create(:eng_word => "hurdle", :frequency => 1) 
        Vocentry.create(:eng_word => "hussy", :frequency => 1) 
        Vocentry.create(:eng_word => "hustle", :frequency => 1) 
        Vocentry.create(:eng_word => "i am in a pickle", :frequency => 1) 
        Vocentry.create(:eng_word => "i dig that!", :frequency => 1) 
        Vocentry.create(:eng_word => "i don't give a hoot", :frequency => 1) 
        Vocentry.create(:eng_word => "icky", :frequency => 1) 
        Vocentry.create(:eng_word => "ilk", :frequency => 1) 
        Vocentry.create(:eng_word => "impassioned", :frequency => 1) 
        Vocentry.create(:eng_word => "implausible", :frequency => 1) 
        Vocentry.create(:eng_word => "in one go", :frequency => 1) 
        Vocentry.create(:eng_word => "inane", :frequency => 1) 
        Vocentry.create(:eng_word => "internecine", :frequency => 1) 
        Vocentry.create(:eng_word => "intertwine", :frequency => 1) 
        Vocentry.create(:eng_word => "is wary of", :frequency => 1) 
        Vocentry.create(:eng_word => "it smacks of", :frequency => 1) 
        Vocentry.create(:eng_word => "jaded", :frequency => 1) 
        Vocentry.create(:eng_word => "jagged", :frequency => 1) 
        Vocentry.create(:eng_word => "jeer at", :frequency => 1) 
        Vocentry.create(:eng_word => "jeopardize", :frequency => 1) 
        Vocentry.create(:eng_word => "jet black", :frequency => 1) 
        Vocentry.create(:eng_word => "jettison", :frequency => 1) 
        Vocentry.create(:eng_word => "jitters", :frequency => 1) 
        Vocentry.create(:eng_word => "jolt", :frequency => 1) 
        Vocentry.create(:eng_word => "josh", :frequency => 1) 
        Vocentry.create(:eng_word => "jot down", :frequency => 1) 
        Vocentry.create(:eng_word => "jump on the bandwagon", :frequency => 1) 
        Vocentry.create(:eng_word => "jumpy", :frequency => 1) 
        Vocentry.create(:eng_word => "keats (np)", :frequency => 1) 
        Vocentry.create(:eng_word => "kelp", :frequency => 1) 
        Vocentry.create(:eng_word => "keyed up", :frequency => 1) 
        Vocentry.create(:eng_word => "kinky", :frequency => 1) 
        Vocentry.create(:eng_word => "kudos", :frequency => 1) 
        Vocentry.create(:eng_word => "ladle", :frequency => 1) 
        Vocentry.create(:eng_word => "lame", :frequency => 1) 
        Vocentry.create(:eng_word => "lapels", :frequency => 1) 
        Vocentry.create(:eng_word => "lash out", :frequency => 1) 
        Vocentry.create(:eng_word => "leaden", :frequency => 1) 
        Vocentry.create(:eng_word => "leech", :frequency => 1) 
        Vocentry.create(:eng_word => "leeway", :frequency => 1) 
        Vocentry.create(:eng_word => "litigation", :frequency => 1) 
        Vocentry.create(:eng_word => "loaf", :frequency => 1) 
        Vocentry.create(:eng_word => "loins", :frequency => 1) 
        Vocentry.create(:eng_word => "loiter", :frequency => 1) 
        Vocentry.create(:eng_word => "loosy goosy", :frequency => 1) 
        Vocentry.create(:eng_word => "lore", :frequency => 1) 
        Vocentry.create(:eng_word => "lost their sway", :frequency => 1) 
        Vocentry.create(:eng_word => "ludicrous", :frequency => 1) 
        Vocentry.create(:eng_word => "lull", :frequency => 1) 
        Vocentry.create(:eng_word => "lump", :frequency => 1) 
        Vocentry.create(:eng_word => "lump sum", :frequency => 1) 
        Vocentry.create(:eng_word => "lunge", :frequency => 1) 
        Vocentry.create(:eng_word => "lurch", :frequency => 1) 
        Vocentry.create(:eng_word => "lurching", :frequency => 1) 
        Vocentry.create(:eng_word => "lure", :frequency => 1) 
        Vocentry.create(:eng_word => "lurks", :frequency => 1) 
        Vocentry.create(:eng_word => "luscious", :frequency => 1) 
        Vocentry.create(:eng_word => "make a fool of yourself", :frequency => 1) 
        Vocentry.create(:eng_word => "make a fuss", :frequency => 1) 
        Vocentry.create(:eng_word => "manacling", :frequency => 1) 
        Vocentry.create(:eng_word => "mauled", :frequency => 1) 
        Vocentry.create(:eng_word => "mean well", :frequency => 1) 
        Vocentry.create(:eng_word => "meek", :frequency => 1) 
        Vocentry.create(:eng_word => "mellow", :frequency => 1) 
        Vocentry.create(:eng_word => "mesmerize", :frequency => 1) 
        Vocentry.create(:eng_word => "mesmerized", :frequency => 1) 
        Vocentry.create(:eng_word => "messing around", :frequency => 1) 
        Vocentry.create(:eng_word => "middling", :frequency => 1) 
        Vocentry.create(:eng_word => "mingle", :frequency => 1) 
        Vocentry.create(:eng_word => "mischief-maker", :frequency => 1) 
        Vocentry.create(:eng_word => "mislead", :frequency => 1) 
        Vocentry.create(:eng_word => "momentum", :frequency => 1) 
        Vocentry.create(:eng_word => "moniker", :frequency => 1) 
        Vocentry.create(:eng_word => "motley crew", :frequency => 1) 
        Vocentry.create(:eng_word => "mouth guard", :frequency => 1) 
        Vocentry.create(:eng_word => "moxy", :frequency => 1) 
        Vocentry.create(:eng_word => "muggy", :frequency => 1) 
        Vocentry.create(:eng_word => "muse (n)", :frequency => 1) 
        Vocentry.create(:eng_word => "mussels", :frequency => 1) 
        Vocentry.create(:eng_word => "muster up", :frequency => 1) 
        Vocentry.create(:eng_word => "mystify", :frequency => 1) 
        Vocentry.create(:eng_word => "nab", :frequency => 1) 
        Vocentry.create(:eng_word => "nagging", :frequency => 1) 
        Vocentry.create(:eng_word => "nary", :frequency => 1) 
        Vocentry.create(:eng_word => "navel", :frequency => 1) 
        Vocentry.create(:eng_word => "nebbish", :frequency => 1) 
        Vocentry.create(:eng_word => "negligible", :frequency => 1) 
        Vocentry.create(:eng_word => "nemesis", :frequency => 1) 
        Vocentry.create(:eng_word => "nimble", :frequency => 1) 
        Vocentry.create(:eng_word => "no diggity", :frequency => 1) 
        Vocentry.create(:eng_word => "nominal fee", :frequency => 1) 
        Vocentry.create(:eng_word => "nondescript", :frequency => 1) 
        Vocentry.create(:eng_word => "nose dive", :frequency => 1) 
        Vocentry.create(:eng_word => "nuance", :frequency => 1) 
        Vocentry.create(:eng_word => "nudge", :frequency => 1) 
        Vocentry.create(:eng_word => "nugatory", :frequency => 1) 
        Vocentry.create(:eng_word => "oblivious", :frequency => 1) 
        Vocentry.create(:eng_word => "obnoxious", :frequency => 1) 
        Vocentry.create(:eng_word => "off the fence", :frequency => 1) 
        Vocentry.create(:eng_word => "ominous", :frequency => 1) 
        Vocentry.create(:eng_word => "on", :frequency => 1) 
        Vocentry.create(:eng_word => "on a whim", :frequency => 1) 
        Vocentry.create(:eng_word => "on the go", :frequency => 1) 
        Vocentry.create(:eng_word => "on the prowl", :frequency => 1) 
        Vocentry.create(:eng_word => "otherwise", :frequency => 1) 
        Vocentry.create(:eng_word => "outbreak", :frequency => 1) 
        Vocentry.create(:eng_word => "outlandish", :frequency => 1) 
        Vocentry.create(:eng_word => "outrageous", :frequency => 1) 
        Vocentry.create(:eng_word => "outright", :frequency => 1) 
        Vocentry.create(:eng_word => "overarching", :frequency => 1) 
        Vocentry.create(:eng_word => "overexert", :frequency => 1) 
        Vocentry.create(:eng_word => "overhaul", :frequency => 1) 
        Vocentry.create(:eng_word => "pacifier", :frequency => 1) 
        Vocentry.create(:eng_word => "palliative", :frequency => 1) 
        Vocentry.create(:eng_word => "paltry", :frequency => 1) 
        Vocentry.create(:eng_word => "pamper", :frequency => 1) 
        Vocentry.create(:eng_word => "pandering", :frequency => 1) 
        Vocentry.create(:eng_word => "pantry", :frequency => 1) 
        Vocentry.create(:eng_word => "parable", :frequency => 1) 
        Vocentry.create(:eng_word => "part and parcel", :frequency => 1) 
        Vocentry.create(:eng_word => "patronize", :frequency => 1) 
        Vocentry.create(:eng_word => "pelts", :frequency => 1) 
        Vocentry.create(:eng_word => "perfunctory", :frequency => 1) 
        Vocentry.create(:eng_word => "pesky", :frequency => 1) 
        Vocentry.create(:eng_word => "pettifogging", :frequency => 1) 
        Vocentry.create(:eng_word => "pitching", :frequency => 1) 
        Vocentry.create(:eng_word => "platitude", :frequency => 1) 
        Vocentry.create(:eng_word => "pleats", :frequency => 1) 
        Vocentry.create(:eng_word => "plight", :frequency => 1) 
        Vocentry.create(:eng_word => "plunge", :frequency => 1) 
        Vocentry.create(:eng_word => "plunk down", :frequency => 1) 
        Vocentry.create(:eng_word => "poise", :frequency => 1) 
        Vocentry.create(:eng_word => "pony up", :frequency => 1) 
        Vocentry.create(:eng_word => "portentous", :frequency => 1) 
        Vocentry.create(:eng_word => "pothole", :frequency => 1) 
        Vocentry.create(:eng_word => "potty", :frequency => 1) 
        Vocentry.create(:eng_word => "pout", :frequency => 1) 
        Vocentry.create(:eng_word => "prank", :frequency => 1) 
        Vocentry.create(:eng_word => "prattle", :frequency => 1) 
        Vocentry.create(:eng_word => "preposterous", :frequency => 1) 
        Vocentry.create(:eng_word => "prevaricate", :frequency => 1) 
        Vocentry.create(:eng_word => "prickly", :frequency => 1) 
        Vocentry.create(:eng_word => "primer", :frequency => 1) 
        Vocentry.create(:eng_word => "primpring", :frequency => 1) 
        Vocentry.create(:eng_word => "print run", :frequency => 1) 
        Vocentry.create(:eng_word => "profligacy", :frequency => 1) 
        Vocentry.create(:eng_word => "profligate", :frequency => 1) 
        Vocentry.create(:eng_word => "prong", :frequency => 1) 
        Vocentry.create(:eng_word => "protean", :frequency => 1) 
        Vocentry.create(:eng_word => "protracted", :frequency => 1) 
        Vocentry.create(:eng_word => "prowl", :frequency => 1) 
        Vocentry.create(:eng_word => "prurient", :frequency => 1) 
        Vocentry.create(:eng_word => "pry", :frequency => 1) 
        Vocentry.create(:eng_word => "puffy", :frequency => 1) 
        Vocentry.create(:eng_word => "pull back", :frequency => 1) 
        Vocentry.create(:eng_word => "pull off", :frequency => 1) 
        Vocentry.create(:eng_word => "pulpit", :frequency => 1) 
        Vocentry.create(:eng_word => "pummel", :frequency => 1) 
        Vocentry.create(:eng_word => "pungent", :frequency => 1) 
        Vocentry.create(:eng_word => "punt", :frequency => 1) 
        Vocentry.create(:eng_word => "put someon on", :frequency => 1) 
        Vocentry.create(:eng_word => "put someone on", :frequency => 1) 
        Vocentry.create(:eng_word => "quaint", :frequency => 1) 
        Vocentry.create(:eng_word => "quaintness", :frequency => 1) 
        Vocentry.create(:eng_word => "quandary", :frequency => 1) 
        Vocentry.create(:eng_word => "quants", :frequency => 1) 
        Vocentry.create(:eng_word => "quarrel", :frequency => 1) 
        Vocentry.create(:eng_word => "quash", :frequency => 1) 
        Vocentry.create(:eng_word => "queasiness", :frequency => 1) 
        Vocentry.create(:eng_word => "quelch", :frequency => 1) 
        Vocentry.create(:eng_word => "quibble", :frequency => 1) 
        Vocentry.create(:eng_word => "quibbles", :frequency => 1) 
        Vocentry.create(:eng_word => "quirky", :frequency => 1) 
        Vocentry.create(:eng_word => "raid", :frequency => 1) 
        Vocentry.create(:eng_word => "railings", :frequency => 1) 
        Vocentry.create(:eng_word => "rambunctious", :frequency => 1) 
        Vocentry.create(:eng_word => "rant", :frequency => 1) 
        Vocentry.create(:eng_word => "rat race (competitividad feroz de la vida moderna)", :frequency => 1) 
        Vocentry.create(:eng_word => "raucous", :frequency => 1) 
        Vocentry.create(:eng_word => "raven", :frequency => 1) 
        Vocentry.create(:eng_word => "ravishing", :frequency => 1) 
        Vocentry.create(:eng_word => "razzle", :frequency => 1) 
        Vocentry.create(:eng_word => "reap", :frequency => 1) 
        Vocentry.create(:eng_word => "rebound", :frequency => 1) 
        Vocentry.create(:eng_word => "reel", :frequency => 1) 
        Vocentry.create(:eng_word => "reeling", :frequency => 1) 
        Vocentry.create(:eng_word => "relentless", :frequency => 1) 
        Vocentry.create(:eng_word => "reluctance", :frequency => 1) 
        Vocentry.create(:eng_word => "reluctant", :frequency => 1) 
        Vocentry.create(:eng_word => "removal", :frequency => 1) 
        Vocentry.create(:eng_word => "repentant", :frequency => 1) 
        Vocentry.create(:eng_word => "respite (from respect)", :frequency => 1) 
        Vocentry.create(:eng_word => "revile", :frequency => 1) 
        Vocentry.create(:eng_word => "riddle", :frequency => 1) 
        Vocentry.create(:eng_word => "rig", :frequency => 1) 
        Vocentry.create(:eng_word => "right up front", :frequency => 1) 
        Vocentry.create(:eng_word => "rile", :frequency => 1) 
        Vocentry.create(:eng_word => "rubble", :frequency => 1) 
        Vocentry.create(:eng_word => "rug", :frequency => 1) 
        Vocentry.create(:eng_word => "rumble", :frequency => 1) 
        Vocentry.create(:eng_word => "rummaging", :frequency => 1) 
        Vocentry.create(:eng_word => "run", :frequency => 1) 
        Vocentry.create(:eng_word => "run across", :frequency => 1) 
        Vocentry.create(:eng_word => "sag", :frequency => 1) 
        Vocentry.create(:eng_word => "sanction", :frequency => 1) 
        Vocentry.create(:eng_word => "sassy", :frequency => 1) 
        Vocentry.create(:eng_word => "scab", :frequency => 1) 
        Vocentry.create(:eng_word => "scampered", :frequency => 1) 
        Vocentry.create(:eng_word => "scattershot", :frequency => 1) 
        Vocentry.create(:eng_word => "scavenge", :frequency => 1) 
        Vocentry.create(:eng_word => "scorch", :frequency => 1) 
        Vocentry.create(:eng_word => "scorn", :frequency => 1) 
        Vocentry.create(:eng_word => "scrawny", :frequency => 1) 
        Vocentry.create(:eng_word => "screening services", :frequency => 1) 
        Vocentry.create(:eng_word => "scrum", :frequency => 1) 
        Vocentry.create(:eng_word => "scurvy", :frequency => 1) 
        Vocentry.create(:eng_word => "seams", :frequency => 1) 
        Vocentry.create(:eng_word => "seditious", :frequency => 1) 
        Vocentry.create(:eng_word => "seemingly", :frequency => 1) 
        Vocentry.create(:eng_word => "serendipity", :frequency => 1) 
        Vocentry.create(:eng_word => "shabby", :frequency => 1) 
        Vocentry.create(:eng_word => "shack up", :frequency => 1) 
        Vocentry.create(:eng_word => "shady", :frequency => 1) 
        Vocentry.create(:eng_word => "sham", :frequency => 1) 
        Vocentry.create(:eng_word => "shamble", :frequency => 1) 
        Vocentry.create(:eng_word => "shear", :frequency => 1) 
        Vocentry.create(:eng_word => "shed", :frequency => 1) 
        Vocentry.create(:eng_word => "shield", :frequency => 1) 
        Vocentry.create(:eng_word => "shill", :frequency => 1) 
        Vocentry.create(:eng_word => "shirk", :frequency => 1) 
        Vocentry.create(:eng_word => "shoals", :frequency => 1) 
        Vocentry.create(:eng_word => "shore up", :frequency => 1) 
        Vocentry.create(:eng_word => "shortfall", :frequency => 1) 
        Vocentry.create(:eng_word => "shrill", :frequency => 1) 
        Vocentry.create(:eng_word => "shrivel", :frequency => 1) 
        Vocentry.create(:eng_word => "shroud", :frequency => 1) 
        Vocentry.create(:eng_word => "shudder", :frequency => 1) 
        Vocentry.create(:eng_word => "shun", :frequency => 1) 
        Vocentry.create(:eng_word => "shunning", :frequency => 1) 
        Vocentry.create(:eng_word => "shutt out", :frequency => 1) 
        Vocentry.create(:eng_word => "sinewy", :frequency => 1) 
        Vocentry.create(:eng_word => "skirmish", :frequency => 1) 
        Vocentry.create(:eng_word => "skirt facts", :frequency => 1) 
        Vocentry.create(:eng_word => "skittish", :frequency => 1) 
        Vocentry.create(:eng_word => "slacker", :frequency => 1) 
        Vocentry.create(:eng_word => "slate", :frequency => 1) 
        Vocentry.create(:eng_word => "slated to be", :frequency => 1) 
        Vocentry.create(:eng_word => "sleazy", :frequency => 1) 
        Vocentry.create(:eng_word => "sleight", :frequency => 1) 
        Vocentry.create(:eng_word => "slender", :frequency => 1) 
        Vocentry.create(:eng_word => "slight (n)", :frequency => 1) 
        Vocentry.create(:eng_word => "slimy", :frequency => 1) 
        Vocentry.create(:eng_word => "sloth", :frequency => 1) 
        Vocentry.create(:eng_word => "slouch", :frequency => 1) 
        Vocentry.create(:eng_word => "slouch away", :frequency => 1) 
        Vocentry.create(:eng_word => "slovenly", :frequency => 1) 
        Vocentry.create(:eng_word => "slovenly slope", :frequency => 1) 
        Vocentry.create(:eng_word => "slucker", :frequency => 1) 
        Vocentry.create(:eng_word => "sluffer", :frequency => 1) 
        Vocentry.create(:eng_word => "sluice", :frequency => 1) 
        Vocentry.create(:eng_word => "slump", :frequency => 1) 
        Vocentry.create(:eng_word => "slurred speech", :frequency => 1) 
        Vocentry.create(:eng_word => "slurry", :frequency => 1) 
        Vocentry.create(:eng_word => "smear", :frequency => 1) 
        Vocentry.create(:eng_word => "smirk", :frequency => 1) 
        Vocentry.create(:eng_word => "snarling", :frequency => 1) 
        Vocentry.create(:eng_word => "sneak", :frequency => 1) 
        Vocentry.create(:eng_word => "sneak up", :frequency => 1) 
        Vocentry.create(:eng_word => "sneer at", :frequency => 1) 
        Vocentry.create(:eng_word => "snide", :frequency => 1) 
        Vocentry.create(:eng_word => "snuff out figurative v extinguir", :frequency => 1) 
        Vocentry.create(:eng_word => "snugly", :frequency => 1) 
        Vocentry.create(:eng_word => "solace", :frequency => 1) 
        Vocentry.create(:eng_word => "solicitous", :frequency => 1) 
        Vocentry.create(:eng_word => "sophism", :frequency => 1) 
        Vocentry.create(:eng_word => "sororities", :frequency => 1) 
        Vocentry.create(:eng_word => "spear", :frequency => 1) 
        Vocentry.create(:eng_word => "spearhead", :frequency => 1) 
        Vocentry.create(:eng_word => "spiffy", :frequency => 1) 
        Vocentry.create(:eng_word => "spoofing", :frequency => 1) 
        Vocentry.create(:eng_word => "springboard", :frequency => 1) 
        Vocentry.create(:eng_word => "sprinkle", :frequency => 1) 
        Vocentry.create(:eng_word => "spur", :frequency => 1) 
        Vocentry.create(:eng_word => "spurn", :frequency => 1) 
        Vocentry.create(:eng_word => "sputter", :frequency => 1) 
        Vocentry.create(:eng_word => "squab", :frequency => 1) 
        Vocentry.create(:eng_word => "squabbles", :frequency => 1) 
        Vocentry.create(:eng_word => "squalid", :frequency => 1) 
        Vocentry.create(:eng_word => "squeal on", :frequency => 1) 
        Vocentry.create(:eng_word => "squelch", :frequency => 1) 
        Vocentry.create(:eng_word => "squint", :frequency => 1) 
        Vocentry.create(:eng_word => "squinting", :frequency => 1) 
        Vocentry.create(:eng_word => "squire", :frequency => 1) 
        Vocentry.create(:eng_word => "squirm", :frequency => 1) 
        Vocentry.create(:eng_word => "stale", :frequency => 1) 
        Vocentry.create(:eng_word => "stalemate", :frequency => 1) 
        Vocentry.create(:eng_word => "stalk", :frequency => 1) 
        Vocentry.create(:eng_word => "stalk (v)", :frequency => 1) 
        Vocentry.create(:eng_word => "stalwart", :frequency => 1) 
        Vocentry.create(:eng_word => "stammering", :frequency => 1) 
        Vocentry.create(:eng_word => "stance", :frequency => 1) 
        Vocentry.create(:eng_word => "stand still", :frequency => 1) 
        Vocentry.create(:eng_word => "star", :frequency => 1) 
        Vocentry.create(:eng_word => "starch", :frequency => 1) 
        Vocentry.create(:eng_word => "statter", :frequency => 1) 
        Vocentry.create(:eng_word => "status quo", :frequency => 1) 
        Vocentry.create(:eng_word => "stave off", :frequency => 1) 
        Vocentry.create(:eng_word => "steadfast", :frequency => 1) 
        Vocentry.create(:eng_word => "steed", :frequency => 1) 
        Vocentry.create(:eng_word => "stem", :frequency => 1) 
        Vocentry.create(:eng_word => "stench", :frequency => 1) 
        Vocentry.create(:eng_word => "stern", :frequency => 1) 
        Vocentry.create(:eng_word => "stew", :frequency => 1) 
        Vocentry.create(:eng_word => "stifle", :frequency => 1) 
        Vocentry.create(:eng_word => "stingy", :frequency => 1) 
        Vocentry.create(:eng_word => "stint", :frequency => 1) 
        Vocentry.create(:eng_word => "stir up", :frequency => 1) 
        Vocentry.create(:eng_word => "stooge", :frequency => 1) 
        Vocentry.create(:eng_word => "straddle", :frequency => 1) 
        Vocentry.create(:eng_word => "stranded", :frequency => 1) 
        Vocentry.create(:eng_word => "streaming", :frequency => 1) 
        Vocentry.create(:eng_word => "stride/strode", :frequency => 1) 
        Vocentry.create(:eng_word => "strife", :frequency => 1) 
        Vocentry.create(:eng_word => "stultify", :frequency => 1) 
        Vocentry.create(:eng_word => "stump", :frequency => 1) 
        Vocentry.create(:eng_word => "sturdy", :frequency => 1) 
        Vocentry.create(:eng_word => "stutter", :frequency => 1) 
        Vocentry.create(:eng_word => "stypend/stipend", :frequency => 1) 
        Vocentry.create(:eng_word => "subdue", :frequency => 1) 
        Vocentry.create(:eng_word => "such a bummer", :frequency => 1) 
        Vocentry.create(:eng_word => "sullen", :frequency => 1) 
        Vocentry.create(:eng_word => "supercilious", :frequency => 1) 
        Vocentry.create(:eng_word => "supersede", :frequency => 1) 
        Vocentry.create(:eng_word => "survey", :frequency => 1) 
        Vocentry.create(:eng_word => "swaggering", :frequency => 1) 
        Vocentry.create(:eng_word => "swamped with", :frequency => 1) 
        Vocentry.create(:eng_word => "swanky", :frequency => 1) 
        Vocentry.create(:eng_word => "swap", :frequency => 1) 
        Vocentry.create(:eng_word => "sway", :frequency => 1) 
        Vocentry.create(:eng_word => "sweeping", :frequency => 1) 
        Vocentry.create(:eng_word => "swerve", :frequency => 1) 
        Vocentry.create(:eng_word => "swindle", :frequency => 1) 
        Vocentry.create(:eng_word => "swindler", :frequency => 1) 
        Vocentry.create(:eng_word => "swine", :frequency => 1) 
        Vocentry.create(:eng_word => "swinger", :frequency => 1) 
        Vocentry.create(:eng_word => "swivel", :frequency => 1) 
        Vocentry.create(:eng_word => "swoony", :frequency => 1) 
        Vocentry.create(:eng_word => "tackle", :frequency => 1) 
        Vocentry.create(:eng_word => "take in", :frequency => 1) 
        Vocentry.create(:eng_word => "take up", :frequency => 1) 
        Vocentry.create(:eng_word => "tally", :frequency => 1) 
        Vocentry.create(:eng_word => "tantamount", :frequency => 1) 
        Vocentry.create(:eng_word => "tantrum", :frequency => 1) 
        Vocentry.create(:eng_word => "tap somebody's phone", :frequency => 1) 
        Vocentry.create(:eng_word => "tattas", :frequency => 1) 
        Vocentry.create(:eng_word => "taunt", :frequency => 1) 
        Vocentry.create(:eng_word => "taxonomy", :frequency => 1) 
        Vocentry.create(:eng_word => "tear down", :frequency => 1) 
        Vocentry.create(:eng_word => "teeter", :frequency => 1) 
        Vocentry.create(:eng_word => "tenet", :frequency => 1) 
        Vocentry.create(:eng_word => "tenets", :frequency => 1) 
        Vocentry.create(:eng_word => "tepid", :frequency => 1) 
        Vocentry.create(:eng_word => "terse", :frequency => 1) 
        Vocentry.create(:eng_word => "that's the size of it", :frequency => 1) 
        Vocentry.create(:eng_word => "thaw", :frequency => 1) 
        Vocentry.create(:eng_word => "the nuts and bolts", :frequency => 1) 
        Vocentry.create(:eng_word => "thrash", :frequency => 1) 
        Vocentry.create(:eng_word => "threadbare", :frequency => 1) 
        Vocentry.create(:eng_word => "thrift", :frequency => 1) 
        Vocentry.create(:eng_word => "throb", :frequency => 1) 
        Vocentry.create(:eng_word => "throes", :frequency => 1) 
        Vocentry.create(:eng_word => "thugs", :frequency => 1) 
        Vocentry.create(:eng_word => "tingling", :frequency => 1) 
        Vocentry.create(:eng_word => "to arouse", :frequency => 1) 
        Vocentry.create(:eng_word => "to be at standstill", :frequency => 1) 
        Vocentry.create(:eng_word => "to be bound to", :frequency => 1) 
        Vocentry.create(:eng_word => "to be high", :frequency => 1) 
        Vocentry.create(:eng_word => "to be in a bind", :frequency => 1) 
        Vocentry.create(:eng_word => "to be mugged", :frequency => 1) 
        Vocentry.create(:eng_word => "to be remiss", :frequency => 1) 
        Vocentry.create(:eng_word => "to befuddle", :frequency => 1) 
        Vocentry.create(:eng_word => "to break even", :frequency => 1) 
        Vocentry.create(:eng_word => "to bug", :frequency => 1) 
        Vocentry.create(:eng_word => "to cope", :frequency => 1) 
        Vocentry.create(:eng_word => "to feel weepy", :frequency => 1) 
        Vocentry.create(:eng_word => "to fret", :frequency => 1) 
        Vocentry.create(:eng_word => "to have get up and go", :frequency => 1) 
        Vocentry.create(:eng_word => "to jerk", :frequency => 1) 
        Vocentry.create(:eng_word => "to latch on", :frequency => 1) 
        Vocentry.create(:eng_word => "to loosen up", :frequency => 1) 
        Vocentry.create(:eng_word => "to pass muster", :frequency => 1) 
        Vocentry.create(:eng_word => "to raise a stink", :frequency => 1) 
        Vocentry.create(:eng_word => "to run errands", :frequency => 1) 
        Vocentry.create(:eng_word => "to spoil (child)", :frequency => 1) 
        Vocentry.create(:eng_word => "to sue", :frequency => 1) 
        Vocentry.create(:eng_word => "to take a stand", :frequency => 1) 
        Vocentry.create(:eng_word => "to take the plunge (take a risk) arriesgarse", :frequency => 1) 
        Vocentry.create(:eng_word => "toddle", :frequency => 1) 
        Vocentry.create(:eng_word => "toehold", :frequency => 1) 
        Vocentry.create(:eng_word => "toiling", :frequency => 1) 
        Vocentry.create(:eng_word => "tomboy", :frequency => 1) 
        Vocentry.create(:eng_word => "tool", :frequency => 1) 
        Vocentry.create(:eng_word => "toss and turn", :frequency => 1) 
        Vocentry.create(:eng_word => "tote", :frequency => 1) 
        Vocentry.create(:eng_word => "toting from tote", :frequency => 1) 
        Vocentry.create(:eng_word => "tout (v)", :frequency => 1) 
        Vocentry.create(:eng_word => "travesty", :frequency => 1) 
        Vocentry.create(:eng_word => "treacherous", :frequency => 1) 
        Vocentry.create(:eng_word => "tuck in", :frequency => 1) 
        Vocentry.create(:eng_word => "turd", :frequency => 1) 
        Vocentry.create(:eng_word => "turmoil", :frequency => 1) 
        Vocentry.create(:eng_word => "turn out (for) to attend", :frequency => 1) 
        Vocentry.create(:eng_word => "turnaround nm tiempo de respuesta tras llegada", :frequency => 1) 
        Vocentry.create(:eng_word => "turnips", :frequency => 1) 
        Vocentry.create(:eng_word => "turnout", :frequency => 1) 
        Vocentry.create(:eng_word => "tween (ager)", :frequency => 1) 
        Vocentry.create(:eng_word => "twinkle", :frequency => 1) 
        Vocentry.create(:eng_word => "two pronged", :frequency => 1) 
        Vocentry.create(:eng_word => "umpire", :frequency => 1) 
        Vocentry.create(:eng_word => "unbidden", :frequency => 1) 
        Vocentry.create(:eng_word => "undermine", :frequency => 1) 
        Vocentry.create(:eng_word => "uneventful", :frequency => 1) 
        Vocentry.create(:eng_word => "unfathomable", :frequency => 1) 
        Vocentry.create(:eng_word => "unhinged", :frequency => 1) 
        Vocentry.create(:eng_word => "unravel", :frequency => 1) 
        Vocentry.create(:eng_word => "unruffled", :frequency => 1) 
        Vocentry.create(:eng_word => "unvetted?", :frequency => 1) 
        Vocentry.create(:eng_word => "unwavering", :frequency => 1) 
        Vocentry.create(:eng_word => "unwieldy", :frequency => 1) 
        Vocentry.create(:eng_word => "unwitting", :frequency => 1) 
        Vocentry.create(:eng_word => "up to here/now", :frequency => 1) 
        Vocentry.create(:eng_word => "upbeat", :frequency => 1) 
        Vocentry.create(:eng_word => "upend", :frequency => 1) 
        Vocentry.create(:eng_word => "uproarious", :frequency => 1) 
        Vocentry.create(:eng_word => "verbose", :frequency => 1) 
        Vocentry.create(:eng_word => "vested interest", :frequency => 1) 
        Vocentry.create(:eng_word => "vicarious", :frequency => 1) 
        Vocentry.create(:eng_word => "waffle", :frequency => 1) 
        Vocentry.create(:eng_word => "wail", :frequency => 1) 
        Vocentry.create(:eng_word => "wailing", :frequency => 1) 
        Vocentry.create(:eng_word => "ward", :frequency => 1) 
        Vocentry.create(:eng_word => "ward heeler", :frequency => 1) 
        Vocentry.create(:eng_word => "ward of", :frequency => 1) 
        Vocentry.create(:eng_word => "watch it", :frequency => 1) 
        Vocentry.create(:eng_word => "watch out for", :frequency => 1) 
        Vocentry.create(:eng_word => "waver", :frequency => 1) 
        Vocentry.create(:eng_word => "wean off", :frequency => 1) 
        Vocentry.create(:eng_word => "weary", :frequency => 1) 
        Vocentry.create(:eng_word => "welder", :frequency => 1) 
        Vocentry.create(:eng_word => "whimsical", :frequency => 1) 
        Vocentry.create(:eng_word => "whiner", :frequency => 1) 
        Vocentry.create(:eng_word => "whipping", :frequency => 1) 
        Vocentry.create(:eng_word => "whisked away", :frequency => 1) 
        Vocentry.create(:eng_word => "wield", :frequency => 1) 
        Vocentry.create(:eng_word => "wimpy", :frequency => 1) 
        Vocentry.create(:eng_word => "wince", :frequency => 1) 
        Vocentry.create(:eng_word => "wistful", :frequency => 1) 
        Vocentry.create(:eng_word => "wit", :frequency => 1) 
        Vocentry.create(:eng_word => "withdraw from", :frequency => 1) 
        Vocentry.create(:eng_word => "wither", :frequency => 1) 
        Vocentry.create(:eng_word => "wobble", :frequency => 1) 
        Vocentry.create(:eng_word => "woe", :frequency => 1) 
        Vocentry.create(:eng_word => "woebegone", :frequency => 1) 
        Vocentry.create(:eng_word => "woes", :frequency => 1) 
        Vocentry.create(:eng_word => "wolf down", :frequency => 1) 
        Vocentry.create(:eng_word => "woo", :frequency => 1) 
        Vocentry.create(:eng_word => "worn out", :frequency => 1) 
        Vocentry.create(:eng_word => "wrangle", :frequency => 1) 
        Vocentry.create(:eng_word => "wrench", :frequency => 1) 
        Vocentry.create(:eng_word => "zit", :frequency => 1) 
      end
      def self.down
            Vocentry.delete_all
      end
end

